BECLEVER APP

PRIVACY POLICY

The confidentiality of the app is guaranteed by the developer and verified by the store from which the app was downloaded.

The application has a built-in voting feature, which uses only THE NUMBER of this device-application for identification WHICH IS SENT AND STORED ONLY IN THE GOOGLE FIREBASE DATABASE. The application does not use any other identification data as well as personal information.

IF YOU DO NOT AGREE WITH THIS SIMPLY DO NOT USE THIS APP.

BECLEVER app receives the application number from the system something like this: a3cb5NFfx6d31ad0 and send it to Google Firebase database. Sometimes this number is being changed itself. When this happens, the application updates the record in the Google Firebase database. This ensures the relevance of the number of users of the application as well as the number of users who voted for the adoption of the law prohibiting hidden advertising of malicious goods and on other topics. The developer believes that it is completely safe for the user.

code_

deviceID = Settings.Secure.getString(getApplicationContext() .getContentResolver(), Settings.Secure.ANDROID_ID);

Contacts: FilmsDataFromSam@gmail.com
